sudo: false
language: python

python:
  - "2.7"

cache:
  # pip: true  # We have overridden the default install step, caching manually
  # ref: <https://docs.travis-ci.com/user/caching/#Arbitrary-directories>
  - directories:
      - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
      - $HOME/.pip-cache
  - apt

addons:
  postgresql: '9.4'
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

services:
  - docker

before_install:
  # bust only the the part of the cache that we are frequently changing
  - pip uninstall --yes psqlgraph gdcdictionary gdcdatamodel || true

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - psql -c "create database test_userapi" -U postgres
  - userdatamodel-init --db test_userapi
  - pip freeze
  - python bin/setup_test_database.py

# command to run tests
script:
  PYTHONPATH=. py.test -vv tests/system_test.py tests/graphql/test_graphql.py

after_script:
- python-codacy-coverage -r coverage.xml